### ISSUE TITLE
GPG 2.1 requires --pinentry-mode loopback to specify passphrase

### ISSUE THREAD

**Issue by GrahamCobb** [zertrin/duplicity-backup.sh#145]
After upgrading gnupg to V2.1, my unattended duplicty-backup backups stopped working with the following error message:

```
gpg: signing failed: Inappropriate ioctl for device
```

The problem is that I was supplying the passphrase in the config file but gpg now needs the `--pinentry-mode loopback` option to be able to use that. This means adding `--gpg-options "--pinentry-mode loopback"` to the duplicity command. Note that getting the correct quoting is error-prone if doing that using STATIC_OPTIONS.

It would be nice if duplicity-backup automatically added `--gpg-options "--pinentry-mode loopback"` to the duplicity command if the PASSPHRASE is set.  

If that is not possible then, at the very least, please expand the PASSPHRASE comment in the example conf file to explain that `--gpg-options --pinentry-mode=loopback` must be included in STATIC_OPTIONS (that seems to be the best form to recommend to minimise quoting problems).

**Comment by zertrin** [comment]
Hi, thanks for reporting!

Well since that's not the first time that adding options to GPG comes up as an issue, I'm thinking about adding a separate GPG_OPTIONS variable where users could add GPG-related options easily. Not sure yet how quoting issues will turn out.

**Comment by zertrin** [comment]
Hi, I've added a new variable `GPG_OPTIONS` to the config file and added some description for this issue in the comment there. However I haven't tested it really. Could you have a look at it and give some feedback as to whether this helps solving your issue?

**Comment by GrahamCobb** [comment]
Yes, I have removed the option from STATIC_OPTIONS and added using the suggested GPG_OPTIONS:

GPG_OPTIONS="--no-show-photos --pinentry-mode loopback"

It seems to be working well.

Thanks for adding this.

**Comment by arichiardi** [comment]
Just wanted to say that I am successfully using `--verify-options no-show-photos` as well ;)
