### ISSUE TITLE
How to disable splitting of the backup archive?

### ISSUE THREAD

**Issue by syst0m** [zertrin/duplicity-backup.sh#153]
Full backup produced 23 vol(X).difftar.gz files.

This seems like a hassle and makes listing through, for example, 7 daily full backups (x23 volumes) in an S3 bucket a pain in the ass. 8)

I don't see any command line switch to disable this. How to get only one backup file per run?

**Comment by zertrin** [comment]
Refer to duplicity's documentation and use the static option parameter in the configuration file of this script.

**Comment by syst0m** [comment]
okiedoke, thnx for the tip
