### ISSUE TITLE
Cron causes premission denied error

### ISSUE THREAD

**Issue by able2doit** [zertrin/duplicity-backup.sh#159]
A cron.daily job is a file containing "duplicity-backup.sh -c duplicity-backup.conf", when the log shows an error: 
"Giving up after 5 attempts. IOError: [Errno 13] Permission denied: '/media/nfs/centre.sdb1/Backups.master/duplicity-full-signatures.20170711T213345Z.sigtar.gpg'" followed by: 
"duplicity-backup.sh-dev/duplicity-backup.sh: line 464: 22377 Segmentation fault      ${MAILCMD} -s "${EMAIL_SUBJECT}" -a "From: ${EMAIL_FROM}" "${EMAIL_TO}" < "${LOGFILE}"".

The backup is correctly performed when the same command is run in a terminal.
Any ideas?

**Comment by zertrin** [comment]
Hi sorry for the delay. Do you still have this issue?

From what I can see, there are 2 errors, one is related to a remote filesystem (`/media/nfs`), the other is a segmentation fault while calling the mail client to send the email.

In both cases, the errors come from an external program (duplicity in the first case and the mail client in the second case). Without more information, I don't understand how duplicity-backup.sh is involved.

**Comment by able2doit** [comment]
Thanks for coming back.  It's OK now, and I think it was a need for the right ownership/write permission on the remote share.  Not down to duplicity-backup.sh-dev which is a great program even if duplicity takes considerable configuring to get to work.
