### ISSUE TITLE
Send one single notification to Slack for multiple script runs

### ISSUE THREAD

**Issue by iamShantanu101** [zertrin/duplicity-backup.sh#160]
Hello,

Is it possible to send one single slack to notifications to slack channel on multiple invocations of duplicity backup scripts?

For ex. duplicity backs up multiple directories based on config files and sends the notification once it completes. This happens everytime the script is run.

Is it possible, like, say, run script 10 times, save the responses and then at the, send a collective report to slack channel along with the details?

**Comment by zertrin** [comment]
Well, no, for this you'll have to code some wrapper around this script by yourself I guess. The current wrapper is completely stateless, so there's no way for it to know the concept of beginning or end of multiple invocations.
