### ISSUE TITLE
VERSION file issues

### ISSUE THREAD

**Issue by regelga** [zertrin/duplicity-backup.sh#164]
1.  The new VERSION file makes an external dependency for the script.  Previously it worked fine standalone.
2.  "VERSION" is a very generic filename, may potentially clash with other software, and is difficult to relate to this script when loaded in directories with other files.

Suggestion:  put the version number in the script itself.

**Comment by zertrin** [comment]
You were right. I guess what happened is that I first created the VERSION file, and then much later implemented a way to output the version from the script.

I've followed your suggestion in v1.4.2.

Thanks for reporting!
