### ISSUE TITLE
Hubic Support

### ISSUE THREAD

**Issue by jaycuse** [zertrin/duplicity-backup.sh#165]
It would be nice to have Hubic support.

Hubic requires pyrax (https://developer.rackspace.com/sdks/python/). So it would almost require a separate python script for the get_remote_file_size function. I assume this is the main limitation. However, I only skimmed through the script. I'm hoping I could take a crack at it at some point. My rack space sdk knowledge is limited.

Someone with the proper experience could probably get this done fast compared to me.

**Comment by zertrin** [comment]
Hi,

Is Hubic already supported by duplicity?

If no, then that's a prerequisite. If yes, what specifically do you mean about what needs to be implemented in this wrapper script for Hubic?

In any case, as I don't use it, there is little chance that I will implement it myself, so a community PR would be required.

**Comment by jaycuse** [comment]
Yes, I meant adding hubic support for the wrapper. Not sure what more information I can give, it's all in the original request.

I was going to start working on it myself, however I won't be in the end. I decided to use a different backup solution since I was having other problems with duplicity that have nothing to do with the wrapper script.

Feel free to either close enhancement request or keep it open in case someone comes along and wants to work on it.

**Comment by xmatthias** [comment]
hubic is supported by duplicity (as well as in this backup script).
From the [duplicity man page](http://duplicity.nongnu.org/duplicity.1.html) in the hubic section:
`cf+hubic://container_name`
According to the man-page, this requires the pyrax package to be installed on the system.
By simply setting `DEST="cf+hubic://duplicityBackup1"` in the backup script, the backup works fine.
The only improvement to the backup-script for this backend "could" be to add it as a sample to the configuration - but i don't think the samples intend to be complete - but to give a good basic overwiew.

I recently wrote a blog post about this topic (duplicity with hubic) if you are interrested in more information: https://blog.xmatthias.com/duplicity-hubic/
