### ISSUE TITLE
Issue with PASSPHRASE and the ` character

### ISSUE THREAD

**Issue by woftor** [zertrin/duplicity-backup.sh#166]
I use very complicated (random generated) passwords for my backups and I found out that this sometimes gives errors because of the ` character This issue occurs because in the default .conf file the PASSPHRASE variable is surrounded by double quotes **(")**.

**PASSPHRASE="`gLm~5`k1Ph6ioy*k%fV*a2"**

To solve this, use single quotes **(')** and everything is well, like this:

**PASSPHRASE='`gLm~5`k1Ph6ioy*k%fV*a2'**

I think it should be considered to change this in the example .conf.

P.S. Note that the  - ` -  character (between the dashes) also gives errors (is not shown) on github in these examples. The (bogus) password actually contains two of these characters (1st and 7th) but these are not shown because of the makeup in github - there are spaces instead.

This replacement may also resolve issue #144

**Comment by zertrin** [comment]
Done in commit dba25a57. Thanks for the suggestion. I did think about it some time ago but forgot before actually doing the change.

**Comment by woftor** [comment]
Wonderful. Thanks.
